In [24]:
import pandas as pd 

dataframe = pd.DataFrame({
    "Americano": [5628, 6239],
    "Latte": [12426, 25384],
    "Espresso": [852, 756],
    "Cappuccino": [8522, 7561],
}, index=["2021", "2022"] )
dataframe.index.name = "Sales by Year"

dataframe

               Americano  Latte  Espresso  Cappuccino
Sales by Year
2021                5628  12426       852        8522
2022                6239  25384       756        7561

In [25]:
dataframe.loc["Total"] = dataframe.sum()

dataframe

               Americano  Latte  Espresso  Cappuccino
Sales by Year
2021                5628  12426       852        8522
2022                6239  25384       756        7561
Total              11867  37810      1608       16083

In [26]:
dataframe.loc["YoY Growth"] = (dataframe.loc["2022"] - dataframe.loc["2021"]) / dataframe.loc["2021"] * 100

dataframe

                  Americano         Latte     Espresso    Cappuccino
Sales by Year
2021            5628.000000  12426.000000   852.000000   8522.000000
2022            6239.000000  25384.000000   756.000000   7561.000000
Total          11867.000000  37810.000000  1608.000000  16083.000000
YoY Growth        10.856432    104.281346   -11.267606    -11.276696

The lowest selling beverage type between 2021 and 2022 was Cappuccino. The highest selling beverage type during this same period was Latte.

*Which products deserve higher marketing spend? Are there any drinks that might need to be phased out or redesigned based on their YoY trajectory?*

The products that deserve higher marketing spend are lattes because of their massive year-over-year growth. It makes the most sense to capitalize on this growth and "ride the wave". Americanos may not be worth the extra investment since they're growing so slowly. The drinks that likely need to be phased out or redesigned are espressos and cappuccinos, because of their declining YoY trajectory.