In [32]:
from pathlib import Path

import pandas as pd

CSV_FILES = ["Coffee_export-1.csv", "Coffee_import-1.csv", "Coffee_production-1.csv"]

sentinel = -2147483648
df_exports = pd.read_csv(CSV_FILES[0], skipinitialspace=True, na_values=[sentinel])
# na_values added because the CSVs encode every NaN cell with a sentinel value

df_exports.head()

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
0,Angola,5040000,4260000,4800000,2340000,480000,2460000,3120000,3000000,3240000,...,480000,480000,360000,540000.0,660000.0,660000,540000,540000,1380000.0,43320000
1,Bolivia (Plurinational State of),9360000,4440000,5760000,2820000,5040000,5640000,7380000,6660000,5820000,...,4440000,3780000,3300000,3720000.0,1800000.0,1320000,1560000,1320000,1200000.0,137460000
2,Brazil,1016160000,1270980000,1127460000,1070280000,1036380000,868080000,915060000,1008060000,1088640000,...,2028360000,1712940000,1899060000,NaN,NaN,2056140000,1855500000,2138220000,NaN,33807709056
3,Burundi,35100000,41280000,38760000,25080000,30480000,31680000,13440000,31740000,22440000,...,13080000,23520000,11700000,15120000.0,13800000.0,12240000,10140000,12120000,17580000.0,646200000
4,Cameroon,156660000,105120000,98760000,42300000,32760000,24420000,33840000,82080000,44760000,...,29400000,37320000,16320000,22500000.0,23400000.0,16860000,14700000,17220000,15000000.0,1399920000

In [33]:
print("=== INFO ===")
df_exports.info()
print("=== COLUMNS ===")
df_exports.columns

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       55 non-null     str
 1   1990          55 non-null     int64
 2   1991          55 non-null     int64
 3   1992          55 non-null     int64
 4   1993          55 non-null     int64
 5   1994          55 non-null     int64
 6   1995          55 non-null     int64
 7   1996          55 non-null     int64
 8   1997          55 non-null     int64
 9   1998          55 non-null     int64
 10  1999          55 non-null     int64
 11  2000          55 non-null     int64
 12  2001          55 non-null     int64
 13  2002          55 non-null     int64
 14  2003          55 non-null     int64
 15  2004          55 non-null     int64
 16  2005          55 non-null     int64
 17  2006          55 non-null     int64
 18  2007          55 non-null     int64
 19  2008          55 non-null     int64
 20  2009          55 non-null     int64
 21  2010          55 non-null     int64
 22  2011          55 non-null     int64
 23  2012          55 non-null     int64
 24  2013          55 non-null     int64
 25  2014          54 non-null     float64
 26  2015          54 non-null     float64
 27  2016          55 non-null     int64
 28  2017          55 non-null     int64
 29  2018          55 non-null     int64
 30  2019          54 non-null     float64
 31  Total_export  55 non-null     int64
dtypes: float64(3), int64(28), str(1)
memory usage: 13.9 KB
=== COLUMNS ===

Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_export'],
      dtype='str')

In [34]:
print("=== SHAPE ===")
df_exports.shape

=== SHAPE ===

(55, 32)

In [35]:
print("=== MISSING ===")
df_exports.isna().sum()

=== MISSING ===

Country         0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            1
2015            1
2016            0
2017            0
2018            0
2019            1
Total_export    0
dtype: int64

In [36]:
df_imports = pd.read_csv(CSV_FILES[1], skipinitialspace=True)

df_imports.head()

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
0,Austria,112800000,123480000,132360000,110160000,85020000,73860000,72600000,77640000,77580000,...,87120000,93540000,93300000,91500000,90780000,89700000,87600000,85740000,86880000,2765760000
1,Belgium,0,0,0,0,0,0,0,0,0,...,349680000,340080000,330120000,312720000,332040000,363120000,340620000,344520000,371940000,6240540000
2,Belgium/Luxembourg,120900000,104760000,109680000,123780000,135720000,144060000,151560000,152640000,214800000,...,0,0,0,0,0,0,0,0,0,1257900000
3,Bulgaria,16080000,12000000,10920000,23820000,27780000,30900000,16320000,17640000,20520000,...,28920000,33600000,36540000,37260000,40920000,46740000,42420000,44220000,47100000,830700000
4,Croatia,0,0,10080000,9780000,11580000,19200000,19320000,23100000,20340000,...,23460000,23040000,24780000,25200000,26220000,28740000,26340000,26760000,27960000,622080000

In [37]:
print("=== INFO ===")
df_imports.info()
print("=== COLUMNS ===")
df_imports.columns

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 32 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country       35 non-null     str
 1   1990          35 non-null     int64
 2   1991          35 non-null     int64
 3   1992          35 non-null     int64
 4   1993          35 non-null     int64
 5   1994          35 non-null     int64
 6   1995          35 non-null     int64
 7   1996          35 non-null     int64
 8   1997          35 non-null     int64
 9   1998          35 non-null     int64
 10  1999          35 non-null     int64
 11  2000          35 non-null     int64
 12  2001          35 non-null     int64
 13  2002          35 non-null     int64
 14  2003          35 non-null     int64
 15  2004          35 non-null     int64
 16  2005          35 non-null     int64
 17  2006          35 non-null     int64
 18  2007          35 non-null     int64
 19  2008          35 non-null     int64
 20  2009          35 non-null     int64
 21  2010          35 non-null     int64
 22  2011          35 non-null     int64
 23  2012          35 non-null     int64
 24  2013          35 non-null     int64
 25  2014          35 non-null     int64
 26  2015          35 non-null     int64
 27  2016          35 non-null     int64
 28  2017          35 non-null     int64
 29  2018          35 non-null     int64
 30  2019          35 non-null     int64
 31  Total_import  35 non-null     int64
dtypes: int64(31), str(1)
memory usage: 8.9 KB
=== COLUMNS ===

Index(['Country', '1990', '1991', '1992', '1993', '1994', '1995', '1996',
       '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014',
       '2015', '2016', '2017', '2018', '2019', 'Total_import'],
      dtype='str')

In [38]:
print("=== ROWS ===")
df_imports["Country"].to_numpy()

=== ROWS ===

array(['Austria', 'Belgium', 'Belgium/Luxembourg', 'Bulgaria', 'Croatia',
       'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France',
       'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia',
       'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland',
       'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden',
       'Japan', 'Norway', 'Russian Federation', 'Switzerland', 'Tunisia',
       'United Kingdom', 'United States of America'], dtype=object)

In [39]:
print("=== SHAPE ===")
df_imports.shape

=== SHAPE ===

(35, 32)

In [40]:
print("=== MISSING ===")
df_imports.isna().sum()

=== MISSING ===

Country         0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
2017            0
2018            0
2019            0
Total_import    0
dtype: int64

In [41]:
df_production = pd.read_csv(CSV_FILES[2], skipinitialspace=True)

df_production.head()

,Country,Coffee type,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
0,Angola,Robusta/Arabica,3.000000e+06,4.740000e+06,4.680000e+06,1.980000e+06,4.620000e+06,3.720000e+06,4.260000e+06,3.840000e+06,...,1.740000e+06,1.980000e+06,2.100000e+06,2.340000e+06,2.460000e+06,2.700000e+06,2.100000e+06,2.520000e+06,3.120000e+06,8.208000e+07
1,Bolivia (Plurinational State of),Arabica,7.380000e+06,6.240000e+06,7.200000e+06,3.060000e+06,7.020000e+06,8.520000e+06,7.500000e+06,8.460000e+06,...,7.920000e+06,6.300000e+06,7.200000e+06,6.000000e+06,5.040000e+06,4.680000e+06,5.040000e+06,4.980000e+06,4.860000e+06,2.070000e+08
2,Brazil,Arabica/Robusta,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10
3,Burundi,Arabica/Robusta,2.922000e+07,4.002000e+07,3.720000e+07,2.358000e+07,3.984000e+07,2.604000e+07,2.406000e+07,1.500000e+07,...,1.224000e+07,2.436000e+07,9.780000e+06,1.488000e+07,1.614000e+07,1.176000e+07,1.212000e+07,1.224000e+07,1.632000e+07,6.236400e+08
4,Ecuador,Arabica/Robusta,9.024000e+07,1.274400e+08,7.110000e+07,1.241400e+08,1.425600e+08,1.132800e+08,1.195800e+08,7.146000e+07,...,4.950000e+07,4.968000e+07,3.996000e+07,3.864000e+07,3.864000e+07,3.870000e+07,3.744000e+07,2.976000e+07,3.354000e+07,1.900380e+09

In [42]:
print("=== INFO ===")
df_production.info()

=== INFO ===
<class 'pandas.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 33 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country           55 non-null     str
 1   Coffee type       55 non-null     str
 2   1990/91           55 non-null     float64
 3   1991/92           55 non-null     float64
 4   1992/93           55 non-null     float64
 5   1993/94           55 non-null     float64
 6   1994/95           55 non-null     float64
 7   1995/96           55 non-null     float64
 8   1996/97           55 non-null     float64
 9   1997/98           55 non-null     float64
 10  1998/99           55 non-null     float64
 11  1999/00           55 non-null     float64
 12  2000/01           55 non-null     float64
 13  2001/02           55 non-null     float64
 14  2002/03           55 non-null     float64
 15  2003/04           55 non-null     float64
 16  2004/05           55 non-null     float64
 17  2005/06           55 non-null     float64
 18  2006/07           55 non-null     float64
 19  2007/08           55 non-null     float64
 20  2008/09           55 non-null     float64
 21  2009/10           55 non-null     float64
 22  2010/11           55 non-null     float64
 23  2011/12           55 non-null     float64
 24  2012/13           55 non-null     float64
 25  2013/14           55 non-null     float64
 26  2014/15           55 non-null     float64
 27  2015/16           55 non-null     float64
 28  2016/17           55 non-null     float64
 29  2017/18           55 non-null     float64
 30  2018/19           55 non-null     float64
 31  2019/20           55 non-null     float64
 32  Total_production  55 non-null     float64
dtypes: float64(31), str(2)
memory usage: 14.3 KB

In [43]:
print("=== COLUMNS ===")
df_production.columns

=== COLUMNS ===

Index(['Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94',
       '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00',
       '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06',
       '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12',
       '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18',
       '2018/19', '2019/20', 'Total_production'],
      dtype='str')

In [44]:
print("=== ROWS ===")
df_production["Country"].to_numpy()

=== ROWS ===

array(['Angola', 'Bolivia (Plurinational State of)', 'Brazil', 'Burundi',
       'Ecuador', 'Indonesia', 'Madagascar', 'Malawi', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Rwanda', 'Timor-Leste', 'Zimbabwe', 'Congo',
       'Cuba', 'Dominican Republic', 'Haiti', 'Philippines', 'Tanzania',
       'Zambia', 'Cameroon', 'Central African Republic', 'Colombia',
       'Costa Rica', "Côte d'Ivoire", 'Democratic Republic of Congo',
       'El Salvador', 'Equatorial Guinea', 'Ethiopia', 'Gabon', 'Ghana',
       'Guatemala', 'Guinea', 'Guyana', 'Honduras', 'India', 'Jamaica',
       'Kenya', "Lao People's Democratic Republic", 'Liberia', 'Mexico',
       'Nepal', 'Nicaragua', 'Nigeria', 'Panama', 'Sierra Leone',
       'Sri Lanka', 'Thailand', 'Togo', 'Trinidad & Tobago', 'Uganda',
       'Venezuela', 'Viet Nam', 'Yemen'], dtype=object)

In [45]:
print("=== SHAPE ===")
df_production.shape

=== SHAPE ===

(55, 33)

In [46]:
print("=== MISSING ===")
df_production.isna().sum()

=== MISSING ===

Country             0
Coffee type         0
1990/91             0
1991/92             0
1992/93             0
1993/94             0
1994/95             0
1995/96             0
1996/97             0
1997/98             0
1998/99             0
1999/00             0
2000/01             0
2001/02             0
2002/03             0
2003/04             0
2004/05             0
2005/06             0
2006/07             0
2007/08             0
2008/09             0
2009/10             0
2010/11             0
2011/12             0
2012/13             0
2013/14             0
2014/15             0
2015/16             0
2016/17             0
2017/18             0
2018/19             0
2019/20             0
Total_production    0
dtype: int64

#### How many rows and columns does the dataset contain?
The dataset contains 33 columns and 55 rows.

#### What are the column names?
The column names are as follows: 'Country', 'Coffee type', '1990/91', '1991/92', '1992/93', '1993/94', '1994/95', '1995/96', '1996/97', '1997/98', '1998/99', '1999/00', '2000/01', '2001/02', '2002/03', '2003/04', '2004/05', '2005/06', '2006/07', '2007/08', '2008/09', '2009/10', '2010/11', '2011/12', '2012/13', '2013/14', '2014/15', '2015/16', '2016/17', '2017/18', '2018/19', '2019/20', 'Total_production'.

#### What data types are assigned to each column?
Country and coffee type are assigned to strings. All of the other columns are int64's.

#### Are there any missing values?
Yes, there are missing values in the 2014, 2015, and 2019 columns of the Brazil row in the exports CSV.

#### Which span of years is represented?
The span of years represented are 1990 to 2019.

#### Which countries are included in the records?
The countries included in the records for production and exports are Angola, Bolivia, Brazil, Burundi, Ecuador, Indonesia, Madagascar, Malawi, Papua New Guinea, Paraguay, Peru, Rwanda, Timor-Leste, Zimbabwe, Congo, Cuba, Dominican Republic, Haiti, Philippines, Tanzania, Zambia, Cameroon, Central African Republic, Colombia, Costa Rica, Côte d'Ivoire, Democratic Republic of Congo, El Salvador, Equatorial Guinea, Ethiopia, Gabon, Ghana, Guatemala, Guinea, Guyana, Honduras, India, Jamaica, Kenya, Lao People's Democratic Republic, Liberia, Mexico, Nepal, Nicaragua, Nigeria, Panama, Sierra Leone, Sri Lanka, Thailand, Togo, Trinidad & Tobago, Uganda, Venezuela, Vietnam, and Yemen. The countries included in imports are Austria, Belgium, Luxembourg, Bulgaria, Croatia, Cyprus, Czechia, Denmark, Estonia, Finland, France, Germany, Greece, Hungary, Ireland, Italy, Latvia, Lithuania, Malta, Netherlands, Poland, Portugal, Romania, Slovakia, Slovenia, Spain, Sweden, Japan, Norway, Russian Federation, Switzerland, Tunisia, United Kingdom, and United States of America.

In [47]:
print("=== DETAILS ===")
df_exports.describe()

=== DETAILS ===

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_export
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.400000e+01,5.400000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.400000e+01,5.500000e+01
mean,8.800800e+07,8.284691e+07,8.541382e+07,8.200036e+07,7.713600e+07,7.404436e+07,8.472982e+07,8.775055e+07,8.753673e+07,9.397091e+07,...,1.114767e+08,1.183015e+08,1.184389e+08,8.690222e+07,8.759333e+07,1.323622e+08,1.303887e+08,1.381047e+08,1.011022e+08,2.851332e+09
std,1.832890e+08,2.019180e+08,2.031566e+08,1.852049e+08,1.719033e+08,1.471032e+08,1.634044e+08,1.761129e+08,1.836647e+08,2.146255e+08,...,3.121420e+08,3.032438e+08,3.130926e+08,2.368317e+08,2.189238e+08,3.763857e+08,3.407518e+08,3.927493e+08,2.599194e+08,6.261177e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+06
25%,4.020000e+06,3.960000e+06,2.310000e+06,2.220000e+06,1.860000e+06,2.370000e+06,1.680000e+06,2.220000e+06,1.800000e+06,2.220000e+06,...,5.400000e+05,4.500000e+05,3.600000e+05,6.150000e+05,6.600000e+05,6.600000e+05,5.700000e+05,5.100000e+05,4.500000e+05,6.084000e+07
50%,1.578000e+07,9.300000e+06,9.960000e+06,1.308000e+07,9.180000e+06,1.200000e+07,9.360000e+06,1.218000e+07,1.284000e+07,1.806000e+07,...,7.920000e+06,8.220000e+06,4.200000e+06,4.110000e+06,3.810000e+06,4.560000e+06,3.480000e+06,6.660000e+06,3.330000e+06,3.160800e+08
75%,1.055700e+08,8.502000e+07,7.971000e+07,7.818000e+07,8.499000e+07,8.970000e+07,1.055100e+08,9.048000e+07,9.099000e+07,9.414000e+07,...,8.133000e+07,8.862000e+07,7.818000e+07,6.291000e+07,4.978500e+07,6.420000e+07,4.947000e+07,6.234000e+07,5.929500e+07,2.552670e+09
max,1.016160e+09,1.270980e+09,1.127460e+09,1.070280e+09,1.036380e+09,8.680800e+08,9.150600e+08,1.008060e+09,1.088640e+09,1.388940e+09,...,2.028360e+09,1.712940e+09,1.899060e+09,1.565820e+09,1.316640e+09,2.056140e+09,1.855500e+09,2.138220e+09,1.644000e+09,3.380771e+10

In [48]:
print("=== DETAILS ===")
df_imports.describe()

=== DETAILS ===

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total_import
count,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,...,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01,3.500000e+01
mean,1.270834e+08,1.221943e+08,1.357989e+08,1.322023e+08,1.286126e+08,1.240646e+08,1.334674e+08,1.389651e+08,1.418863e+08,1.464549e+08,...,1.916794e+08,1.940109e+08,1.987337e+08,2.057606e+08,2.080800e+08,2.187960e+08,2.161097e+08,2.227629e+08,2.313326e+08,5.069693e+09
std,2.543488e+08,2.435393e+08,2.690354e+08,2.424808e+08,2.178530e+08,2.188911e+08,2.415144e+08,2.500391e+08,2.548447e+08,2.715283e+08,...,3.363666e+08,3.404099e+08,3.453368e+08,3.539295e+08,3.511787e+08,3.667628e+08,3.684394e+08,3.678250e+08,3.854538e+08,8.850559e+09
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.970000e+07
25%,6.300000e+05,4.800000e+05,6.180000e+06,7.890000e+06,8.880000e+06,8.550000e+06,9.750000e+06,1.074000e+07,1.077000e+07,1.176000e+07,...,2.151000e+07,2.163000e+07,2.373000e+07,2.499000e+07,2.595000e+07,2.835000e+07,2.613000e+07,2.937000e+07,2.946000e+07,5.573100e+08
50%,3.444000e+07,3.150000e+07,3.618000e+07,4.008000e+07,4.626000e+07,3.798000e+07,4.458000e+07,4.362000e+07,4.572000e+07,4.740000e+07,...,5.712000e+07,6.456000e+07,6.378000e+07,6.360000e+07,6.264000e+07,6.804000e+07,6.564000e+07,6.960000e+07,7.320000e+07,1.640040e+09
75%,1.168500e+08,1.141200e+08,1.210200e+08,1.169700e+08,1.246500e+08,1.251600e+08,1.335000e+08,1.439100e+08,1.546500e+08,1.491000e+08,...,2.276100e+08,2.300700e+08,2.283900e+08,2.500500e+08,2.665800e+08,2.949900e+08,3.017100e+08,3.242400e+08,3.272400e+08,5.841240e+09
max,1.260420e+09,1.190400e+09,1.376340e+09,1.159740e+09,9.702600e+08,1.026420e+09,1.166700e+09,1.220580e+09,1.261800e+09,1.364760e+09,...,1.565580e+09,1.563360e+09,1.620960e+09,1.653900e+09,1.662480e+09,1.730280e+09,1.769280e+09,1.735080e+09,1.851240e+09,4.250766e+10

In [49]:
print("=== DETAILS ===")
df_production.describe()

=== DETAILS ===

,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
count,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,...,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01,5.500000e+01
mean,1.017055e+08,1.104753e+08,1.074775e+08,1.001007e+08,1.017971e+08,9.525927e+07,1.127029e+08,1.089676e+08,1.187629e+08,1.433280e+08,...,1.541749e+08,1.649280e+08,1.679007e+08,1.639625e+08,1.703193e+08,1.770742e+08,1.785742e+08,1.881415e+08,1.800578e+08,4.104269e+09
std,2.510875e+08,2.668466e+08,3.022180e+08,2.489344e+08,2.510328e+08,1.858680e+08,2.602192e+08,2.430145e+08,3.142337e+08,4.012591e+08,...,4.469919e+08,4.931417e+08,5.030529e+08,4.918727e+08,5.059698e+08,5.225472e+08,5.135587e+08,5.851111e+08,5.390922e+08,1.112550e+10
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.080000e+06
25%,2.430000e+06,3.900000e+06,2.640000e+06,2.130000e+06,2.610000e+06,2.610000e+06,2.340000e+06,2.880000e+06,3.480000e+06,3.540000e+06,...,1.980000e+06,1.710000e+06,2.010000e+06,2.250000e+06,2.310000e+06,1.890000e+06,2.160000e+06,2.190000e+06,2.280000e+06,8.199000e+07
50%,2.766000e+07,2.778000e+07,3.000000e+07,2.652000e+07,2.436000e+07,2.604000e+07,2.406000e+07,1.800000e+07,2.634000e+07,2.184000e+07,...,2.094000e+07,2.004000e+07,1.548000e+07,1.488000e+07,1.758000e+07,1.620000e+07,1.584000e+07,1.860000e+07,1.842000e+07,6.236400e+08
75%,9.216000e+07,9.720000e+07,9.234000e+07,9.486000e+07,1.153200e+08,1.127700e+08,1.139700e+08,9.669000e+07,1.076700e+08,1.211700e+08,...,9.735000e+07,9.189000e+07,7.185000e+07,6.960000e+07,6.657000e+07,6.864000e+07,7.053000e+07,7.806000e+07,7.194000e+07,2.785140e+09
max,1.637160e+09,1.637580e+09,2.076180e+09,1.690020e+09,1.691520e+09,1.083600e+09,1.751820e+09,1.568880e+09,2.205660e+09,2.854680e+09,...,2.915520e+09,3.325080e+09,3.281340e+09,3.198300e+09,3.172260e+09,3.407280e+09,3.164400e+09,3.907860e+09,3.492660e+09,7.508298e+10

In [ ]:
print("=== COFFEE TYPE MEAN ===")
df_production.groupby("Coffee type").mean(numeric_only=True)

# Arabica --> [0, 1, 3]
# Robusta --> [2, 4, 5]

# [0, 1, 3] --> [0: 1000], [1: 2000], [2: 3000]
# sum(): Arabica --> 6000

=== COFFEE TYPE MEAN ===

,1990/91,1991/92,1992/93,1993/94,1994/95,1995/96,1996/97,1997/98,1998/99,1999/00,...,2011/12,2012/13,2013/14,2014/15,2015/16,2016/17,2017/18,2018/19,2019/20,Total_production
Coffee type,,,,,,,,,,,,,,,,,,,,,
Arabica,8.214273e+07,9.427091e+07,8.616273e+07,7.244182e+07,7.799727e+07,8.515636e+07,7.571455e+07,7.906364e+07,7.667182e+07,82500000.0,...,8.909182e+07,9.055909e+07,9.307636e+07,9.433091e+07,98970000.0,1.104491e+08,1.105118e+08,111150000.0,106410000.0,2.634933e+09
Arabica/Robusta,2.999775e+08,3.012450e+08,3.483825e+08,3.115875e+08,3.129450e+08,2.435175e+08,3.269850e+08,2.943675e+08,3.804825e+08,474765000.0,...,4.543350e+08,5.032275e+08,4.852050e+08,4.731825e+08,465060000.0,5.053275e+08,4.778550e+08,575437500.0,515347500.0,1.208355e+10
Robusta,1.776000e+07,2.365600e+07,1.525600e+07,1.325600e+07,1.798000e+07,1.522400e+07,2.605200e+07,2.179600e+07,1.718000e+07,32344000.0,...,1.656800e+07,1.414000e+07,1.688400e+07,1.323200e+07,11460000.0,1.021600e+07,1.239600e+07,14320000.0,13340000.0,5.078520e+08
Robusta/Arabica,1.120440e+08,1.237380e+08,9.997800e+07,1.220280e+08,1.109640e+08,1.189320e+08,1.526280e+08,1.571940e+08,1.543620e+08,178476000.0,...,2.636400e+08,2.840820e+08,3.051960e+08,2.958720e+08,329784000.0,3.113340e+08,3.381540e+08,308418000.0,323928000.0,6.348012e+09

#### Descriptive Statistics
*Explicitly identify the largest values, smallest values, and average values for key metrics. Briefly note any interesting observations or anomalies in these statistical printouts.*

Every column has a minimum value of 0, except for total production.

#### Data Quality Assessment
*Issue 1:* In imports, there is a row for Belgium, Luxembourg, and then Belgium/Luxembourg. This combined statistic of both countries can change the max and mean of each row significantly, which means a less accurate accounting of the data.

*Issue 2:* In exports, Brazil has missing values for 2014, 2015, and 2019. These missing values can cause calculation errors when processing these statistics if not accounted for.

*Issue 3:* Several entries for certain countries have 0's for multiple years. Presumably this means the country was not exporting in those years. These can skew the minimum and mean values, which can affect calculations that depend on those values.

#### Initial Insights
*Which dataset appears to contain the most complete information? Which dataset looks like it will require the most extensive cleaning? What specific types of business questions could these datasets help a global coffee corporation answer?*

The dataset with the most complete information appears to be the imports table. The exports table looks like it will require the most extensive cleaning due to the multiple entries for 0 and the missing values for Brazil. The types of business questions that these datasets could help a global coffee corporation answer are which countries have the most demand year-over-year, which countries have the most supply year-over-year, and what kinds of coffee are the most profitable.